version: "2"
services:
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - "prometheus:/prometheus"
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./prometheus/tg_cassandra.json:/etc/prometheus/tg_cassandra.json"
      - "./prometheus/tg_node.json:/etc/prometheus/tg_node.json"
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - "grafana:/var/lib/grafana"
      - "./grafana/prometheus-datasource.yaml:/etc/grafana/provisioning/datasources/prometheus-datasource.yaml"
      - "./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml"
      - "./grafana/dashboards:/var/lib/grafana/dashboards"
volumes:
  grafana:
  prometheus:  
